### ISSUE TITLE
Create algorithm for getting nutrition plan.

### ISSUE THREAD

**Issue by KacperZielinski** [MWO-iFridge/iFridge-backend#5]
Given: 
daily requirement (less, zero, null);
list of Ingredients.

Return list of recipes.

like
```
public List<Recipe> getNutritionPlan(DailyRequirement dr, List<Ingredient> ingredients) {
    // your creative work
}
```

**Comment by dmisia** [comment]
Daily requirement = zapotrzebowanie kaloryczne w kcal?

**Comment by KacperZielinski** [comment]
Tu miałem na myśli enuma, 
że ziomek musi LESS => schundac (to ja), 
zero, ze utrzymuje wage,
a nulla zastąp czymś ala GAIN => przytyć (nie wiem czemu napisałem null)
